#!/bin/sh
. shared.sh

docker build -t "jusito/build-order:${TAG_BASE}${TAG_POSTFIX}" -f "./base/Dockerfile" .

# push every config
if cd config; then
	for config in *
	do
		docker build -t "${DOCKER_REPO}:${config}${TAG_POSTFIX}" "${config}/."
	done
else
	exit 10
fi
