#!/bin/sh
. hooks/shared.sh

docker push "${DOCKER_REPO}:${TAG_BASE}${TAG_POSTFIX}"

# push every config
if cd config; then
	for config in *
	do
		docker push "${DOCKER_REPO}:${config}${TAG_POSTFIX}"
	done
else
	exit 20
fi
