#!/bin/sh

set -o nounset

# current workdir is /subdir
cd ..

docker build -t "jusito/build-order:latest${TAG_POSTFIX}" -f "./subdir/Dockerfile" .

# push every config
if cd config; then
	for config in *
	do
		docker build -t "${DOCKER_REPO}:${config}${TAG_POSTFIX}" "${config}/."
	done
else
	exit 10
fi
